"""Add status and cancellation_reason to Intervention

Revision ID: 9f77e2da307c
Revises: 
Create Date: 2026-02-09 17:58:15.965257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f77e2da307c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intervention', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
